apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rottingresearch
      tier: worker
  template:
    metadata:
      labels:
        app: rottingresearch
        tier: worker
    spec:
      containers:
      - name: worker
        image: rottingresearch/rottingresearch_worker
        env:
        - name: REDIS_URL
          value: redis://redis:6379
        - name: TMP_CUSTOM_DIR
          value: /tmp_dir/
        volumeMounts:
        - name: cache-volume
          mountPath: /tmp_dir/
